core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views


app_name = 'core'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('myaccount/', views.myaccount, name='myaccount'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('edit-account/', views.edit_account, name='edit_account'),
    path('my-post/', views.my_post, name='my_post'),
]

myblog/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('post/', include('post.urls'))
]

# static
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path

from . import views


app_name = 'post'

urlpatterns = [
    path('detail/<slug:slug>/', views.detail, name='detail'),
    path('tags-post/<int:pk>/', views.tag_post, name='tag_post'),
    path('new/', views.new, name='new'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    
]

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    mobile = models.CharField(max_length=15, blank=True, null=True, unique=True)
    intro = models.TextField(max_length=255, blank=True, null=True)
    profile = models.TextField(max_length=2000, blank=True, null=True)
    
    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

core/views.py
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import User

from post.models import Post


def homepage(request):
    posts = Post.objects.all().order_by('created_at')[:4]

    return render(request, 'core/homepage.html',{
        'posts': posts,
    })

def signup(request):
    if request.method == "POST":
        first_name = request.POST.get('first_name', '')
        last_name = request.POST.get('last_name', '')
        username = request.POST.get('username', '')
        email = request.POST.get('email', '')
        password = request.POST.get('password', '')
        print(password)

        user = User(
            first_name=first_name,
            last_name=last_name,
            username=username,
            email=email,
            # password=password,
        )
        user.set_password(password)
        user.save()

        return redirect('/login/')

    return render(request, 'core/signup.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            auth_login(request, user)
            return redirect('/myaccount/')
        else:
            return render(request, 'core/login.html')
    else:
        return render(request, 'core/login.html')

def myaccount(request):
    posts = Post.objects.filter(author = request.user).order_by('-created_at')

    return render(request, 'core/myaccount.html', {
        'posts': posts,
    })

def edit_account(request):
    if request.method == "POST":
        first_name = request.POST.get('first_name', '')
        last_name = request.POST.get('last_name', '')
        email = request.POST.get('email', '')

        request.user.first_name = first_name
        request.user.last_name = last_name
        request.user.email = email
        
        request.user.save()

        return redirect('/myaccount/')

    return render(request, 'core/edit_account.html')


@login_required
def my_post(request):
    posts = Post.objects.filter(author=request.user).order_by('-created_at')

    return render(request, 'core/my_post.html', { 
        'posts': posts,
    })

core/templates/core/base.html
<!doctype html>

<html lang="en-US">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        {% load static %}
        <link rel="stylesheet" href="/static/css/reset.css"/>
        {% load static %}
        <link rel="stylesheet" href="/static/css/base.css"/>
        {% load static %}
        <link rel="stylesheet" href="/static/css/core.css"/>
        {% load static %}
        <link rel="stylesheet" href="/static/css/post.css"/>
        
        {% comment %} google font {% endcomment %}
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;700&display=swap" rel="stylesheet">
        {% comment %} fontawesome {% endcomment %}
        {% load static %}
        <script src="{% static 'fontawesomefree/js/fontawesome.js' %}"></script>
        {% load static %}
        <script src="{% static 'fontawesomefree/js/solid.js' %}"></script>
        {% load static %}
        <script src="{% static 'fontawesomefree/js/brands.js' %}"></script>
    </head>

    <body>
        <nav>
            <h3><a href="{% url 'core:homepage' %}">Blog Website</a></h3>

            <div class="nav-middle-button">
                <a href="{% url 'core:homepage' %}">Home</a>
                <a href="{% url 'core:my_post' %}">My Blog</a>
                <a href="#">Potfolio</a>
            </div>
            
            {% if request.user.is_authenticated %}
                <a href="{% url 'core:myaccount' %}" class="login-button">{{ request.user.last_name }}, <i class="fa-solid fa-user"></i></a>
            {% else %}
                <a href="{% url 'core:login' %}" class="login-button">Login <i class="fa-solid fa-arrow-right"></i></i></a>
            {% endif %}
        </nav>

        {% block content %}
        {% endblock %}
        
        {% block script %}
        {% endblock %}
    </body>

    <footer>
        <div class="footer-first">
            <h3>My Blog</h3>
            
            <div class="social-media">
                <a href="#"><i class="fa-brands fa-facebook"></i></a>
                <a href="#"><i class="fa-brands fa-square-instagram"></i></a>
                <a href="#"><i class="fa-brands fa-twitter"></i></a>
            </div>
        </div>

        <div class="footer-second">
                <a href="#" class="">Home</a>
                <a href="#" class="">My Blog</a>
                <a href="#" class="">Potfolio</a>
        </div>
    </footer>
</html>

core/templates/core/edit_account.html
{% extends "core/base.html" %}

{% block title %}Edit Account{% endblock %}

{% block content %}
    <main class="login">
        <div class="login-form">
            <h1 class="mt-3">Edit Accountn</h1>

            <form class="mt-2" action="." method="POST">
                {% csrf_token %}

                <div class="name-form">
                    <div>
                        <label>First Name</label></br>
                        <input type='text' class="text-input" name="first_name" value="{{ request.user.first_name }}"></br>
                    </div>
                    <div>
                        <label>Last Name</label></br>
                        <input type='text' class="text-input" name="last_name" value="{{ request.user.last_name }}"></br>
                    </div>
                </div>

                <label class="label mt-1">Email</label></br>
                <input type='email' class="text-input" name="email" value="{{ request.user.email }}"></br>

                <button class="label mt-1">Submit</button>
            </form>
        </div>
    </main>
{% endblock %}

core/templates/core/homepage.html
{% extends "core/base.html" %}

{% block title %}Home Page{% endblock %}

{% block content %}
    <main>
        <h1 class="title"><strong>Read The Blog</strong></h1>

        <div class="list-post">
            {% include "post/partials/list_post.html" %}
        </div>
    </main>
{% endblock %}

core/templates/core/login.html
{% extends "core/base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
    <main class="login">
        <div class="login-form">
            <h1 class="mt-3">My Blog Website</h1>

            <div class="mt-1 register">
                <p>Welcome to our App</p>
                <a href="{% url 'core:signup' %}">Register</a>
            </div>

            <form class="mt-2" method="POST" name="login-form" onSubmit="return validateForm()">
                {% csrf_token %}

                <label for="username">Username</label></br>
                <input type='text' class="text-input" name="username", id="username"></br>

                <label class="label mt-1" for="password">Passoword</label></br>
                <input type='password' class="text-input" name="password", id="password"></br>

                <button class="label mt-1">Submit</button>
            </form>
        </div>
    </main>
{% endblock %}

{% block script %}
    <script>
        function validateForm() {
            let userName = document.querySelector("#username").value;
            let passWord = document.querySelector("#password").value;

            if (userName === '') {
                alert("Please enter username!");
                return false;
            }

            if (passWord === '') {
                alert("Please enter your password!")
                return false
            }   

            return true;
        }
    </script>
{% endblock %}

core/templates/core/my_post.html
{% extends "core/base.html" %}

{% block title %}Your Profile{% endblock %}

{% block content %}
    <main class="myaccount">
        <a href="{% url 'post:new' %}" class="new-post-button mt-1" >New Post</a>

        <h2 class="title">Your Posts</h2>
        <div class="list-your-post mt-2">
            {% for post in posts %}
                <div class="post mt-1">
                    <div class="post-metadata">
                        <p>{{ post.title }}</p>
                        <p class="mt-small"><strong>Date:</strong> {{ post.created_at }}</p>
                        <a href="{% url 'post:detail' post.slug %}" class="mt-small inline-block">See post</a>
                    </div>
                   
                    <div class="edit-delete-button">
                        <a href="{% url 'post:edit' post.id %}" class="new-post-button">Edit</a>
                        <a href="{% url 'post:delete' post.id %}" class="new-post-button">Delete</a>
                    </div>
                </div>
                <hr/>
            {% endfor %}
        </div>
    </main>
{% endblock %}

core/templates/core/myaccount.html
{% extends "core/base.html" %}

{% block title %}Your Profile{% endblock %}

{% block content %}
    <main class="myaccount">
        <div class="mt-2">
            <p class="mt-1"><strong>Username:</strong> {{ request.user.username }}<p>
            <p class="mt-1"><strong>Yourname:</strong> {{ request.user.get_full_name }}</p>
            <p class="mt-1"><strong>Email:</strong> {{ request.user.email }}</p>
        </div>

        <div class="mt-1">
            <a href="{% url 'core:logout' %}">Logout</a> | 
            <a href="{% url 'core:edit_account' %}">Edit Account</a>
        <div>
    </main>
{% endblock %}

core/templates/core/signup.html
{% extends "core/base.html" %}

{% block title %}Signup{% endblock %}

{% block content %}
    <main class="login">
        <div class="login-form">
            <h1 class="mt-3">Sign Up</h1>

            <form class="mt-2" action="." method="POST">
                {% csrf_token %}

                <div class="name-form">
                    <div>
                        <label>First Name</label></br>
                        <input type='text' class="text-input" name="first_name"></br>
                    </div>
                    <div>
                        <label>Last Name</label></br>
                        <input type='text' class="text-input" name="last_name"></br>
                    </div>
                </div>

                <label class="label mt-1">Username</label></br>
                <input type='text' class="text-input" name="username"></br>

                <label class="label mt-1">Email</label></br>
                <input type='email' class="text-input" name="email"></br>

                <label class="label mt-1">Passoword</label></br>
                <input type='password' class="text-input" name="password"></br>

                <button class="label mt-1">Submit</button>
            </form>
        </div>
    </main>
{% endblock %}